connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 87, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 87, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1144, in read_frame
    frame = await Frame.read(
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 87, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1144, in read_frame
    frame = await Frame.read(
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
Starting server!
Player joined: joe
Game will start soon
Game starting now!
here1
here2 teacher
here3 https://cdn-res.keymedia.com/cms/images/ca/126/0299_637453855418575056.jpg
here4
here1
here2 scratch
here3 https://news.mit.edu/sites/default/files/styles/news_article__image_gallery/public/images/201305/20130514110054-1_0_0.jpg?itok=J8bRetuU
here4
here1
here2 round
here3 https://images.homedepot.ca/productimages/p_1001184009.jpg?wid=1000&hei=1000&op_sharpen=1&product-images=l
here4
Game starting now!
here1
here2 drive
here3 https://www.cnet.com/a/img/s-t7ErsqmA21GxePN8vX0YMdrvg=/1200x630/2016/04/15/83350f75-d5fe-4b92-bd3d-df904bd51158/google-drive-icon.jpg
here4
Player left: joe
Reset lobby to waiting state
Player joined: Zdiggity
Game will start soon
Player joined: joe
Game starting now!
here1
here2 applause
here3 https://static.vecteezy.com/system/resources/previews/003/498/451/original/applause-clap-your-hands-illustration-in-flat-style-vector.jpg
here4
here1
here2 pirate
here3 https://www.worldhistory.org/img/r/p/500x600/14535.png?v=1635282902
here4
here1
here2 superman
here3 https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Superman_shield.svg/1200px-Superman_shield.svg.png
here4
here1
here2 abe lincoln
here3 https://deadline.com/wp-content/uploads/2021/02/AP631108094.jpg
here4
here1
here2 wing
here3 https://media.istockphoto.com/vectors/wing-collection-vector-id1292783390?k=20&m=1292783390&s=612x612&w=0&h=SaIAaDqfx1-wiSpjo_fdk4JCc28XELnYv1D35M0rilk=
here4
here1
here2 sing
here3 https://ca-times.brightspotcdn.com/dims4/default/821f7fc/2147483647/strip/true/crop/2098x1134+0+0/resize/1486x803!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F5d%2F6b%2Fdc64d7dc4b1dba5923174fc9bd40%2Fsing2mixingboard.jpg
here4
here1
here2 grapes
here3 https://scx2.b-cdn.net/gfx/news/hires/2022/grapes.jpg
here4
here1
here2 popsicle
here3 https://media.istockphoto.com/vectors/colorful-popsicles-vector-vector-id486828856?k=20&m=486828856&s=612x612&w=0&h=XF_4BZIuzTQZHv4mfARZnrfJVwtrlq7y6O0dKed93xQ=
here4
here1
here2 hat
here3 https://m.media-amazon.com/images/I/61+5hBQrXHL._AC_UL1000_.jpg
here4
Game starting now!
here1
here2 clock
here3 https://m.media-amazon.com/images/I/61mjl672ULL._AC_SL1001_.jpg
here4
here1
here2 sunburn
here3 https://media.glamour.com/photos/575f17ff229ec873777bc83d/1:1/w_728,h_728,c_limit/kim-kardashian-sunburn.jpg
here4
here1
here2 eagle
here3 https://www.eagles.org/wp-content/uploads/2020/07/MG_7021-176-scaled.jpg
here4
here1
here2 jump
here3 https://www.moveplaypaedtherapy.com.au/wp-content/uploads/2019/01/shutterstock_1023694321-1.jpg
here4
here1
here2 fart
here3 https://www.rollingstone.com/wp-content/uploads/2022/01/stephanie-matto.jpg?resize=1800,1200&w=1800
here4
Game starting now!
here1
here2 mailbox
here3 https://homehardware.sirv.com/products/5440/5440052.view?thumb
here4
here1
here2 pikachu
here3 https://ichef.bbci.co.uk/news/640/cpsprodpb/C120/production/_104304494_mediaitem104304493.jpg
here4
here1
here2 list
here3 https://api.backlinko.com/app/uploads/2019/12/the-simple-list-post.png
here4
here1
here2 police
here3 https://portmoodypolice.ca/wp-content/uploads/2021/09/IMG_2478-copy.jpg
here4
Player left: joe
Game starting now!
here1
here2 computer
here3 https://merchandising-assets.bestbuy.ca/bltc8653f66842bff7f/blt15699ad05c6798df/619552bf47db93765d90e738/computing-evergreen-offer-laptops-and-macbooks-m.jpg?width=1800&quality=80&auto=webp
here4
here1
here2 boardgame
here3 https://i.guim.co.uk/img/media/696d305e8fb4ec8e33038325f5e135ad7e6f62b5/0_878_3586_2149/master/3586.jpg?width=1200&quality=85&auto=format&fit=max&s=88bdb4cefb72fbc07627a2eb1e4510cd
here4
here1
here2 scratch
here3 https://addons.mozilla.org/user-media/previews/full/225/225094.png?modified=1622134776
here4
Game starting now!
here1
here2 burp
here3 https://images.theconversation.com/files/334198/original/file-20200512-66675-10mi3j6.jpg?ixlib=rb-1.1.0&rect=484%2C92%2C4271%2C3073&q=20&auto=format&w=320&fit=clip&dpr=2&usm=12&cs=strip
here4
here1
here2 house
here3 https://www.incimages.com/uploaded_files/image/1920x1080/getty_856794670_385651.jpg
here4
Player joined: Jmooy
Player joined: joe
here1
here2 mailbox
here3 https://media.istockphoto.com/photos/open-mailbox-with-letters-on-rural-backgound-picture-id1285800846?b=1&k=20&m=1285800846&s=170667a&w=0&h=XTNubX7I91KkXbAc4KCVa89AzEOhlbaCgt-MIIOzGhs=
here4
here1
here2 library
here3 https://dynaimage.cdn.cnn.com/cnn/c_fill,g_auto,w_1200,h_675,ar_16:9/https%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F211130174309-book-banning-american-library-association-restricted.jpg
here4
here1
here2 pancakes
here3 https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Chocolate-Lover-s-Pancakes_EXPS_TOHCA19_133776_B03_15_3b_rms.jpg
here4
here1
here2 baseball
here3 https://static.wbsc.org/assets/cms/ef40f1a5-a156-3d56-d65a-ed57b3c1cefd.jpg
here4
here1
here2 fish sticks
here3 https://airfryerworld.com/images/Air-Fryer-Frozen-Fish-Sticks-AirFryerWorld-2-500x375.jpg
here4
here1
here2 girlfriend
here3 https://www.yourtango.com/sites/default/files/styles/body_image_default/public/2020/man-woman-loving-embrace-boyfriend-girlfriend.jpg
here4
Game starting now!
here1
here2 learn
here3 https://ahmedalkiremli.com/wp-content/uploads/2014/09/Learn-Ahmed-Al-Kiremli.jpg
here4
Player left: Jmooy
here1
here2 spatula
here3 https://m.media-amazon.com/images/I/61adlhu0KUL._AC_SL1500_.jpg
here4
here1
here2 laptop
here3 https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4LqQX?ver=1f00&q=90&m=6&h=705&w=1253&b=%23FFFFFFFF&f=jpg&o=f&p=140&aim=true
here4
Game starting now!
here1
here2 whistle
here3 https://media.istockphoto.com/vectors/referee-whistle-vector-illustration-vector-id858018820?k=20&m=858018820&s=170667a&w=0&h=IrSrOzbgdb0SeyX_jcRNuQ-sonzlPiWbDp3bp9-hHeU=
here4
here1
here2 panda
here3 https://cdn.mos.cms.futurecdn.net/3n8tRry6fYg7sNyhFDPQwR.jpg
here4
here1
here2 bake sale
here3 https://media.istockphoto.com/photos/bake-sale-cookies-picture-id486207023
here4
here1
here2 spongebob
here3 https://upload.wikimedia.org/wikipedia/en/thumb/3/33/Patrick_Star.svg/1200px-Patrick_Star.svg.png
here4
Player left: joe
Player joined: joe
here1
here2 biscuits
here3 https://www.spendwithpennies.com/wp-content/uploads/2021/10/Easy-Homemade-Buttermilk-Biscuits-SpendWithPennies-8.jpg
here4
Game starting now!
here1
here2 coal
here3 https://www.americangeosciences.org/sites/default/files/styles/ci__650_x_430_/public/CI_259_coal_CSRIO_CCBY3.0_180625_1200x800px_0.jpg?itok=SsQaI4DH
here4
Player joined: Jake
Player left: Jake
here1
here2 sunglasses
here3 https://cdn.shopify.com/s/files/1/0084/1616/5946/products/AGingersSoul_3Q_600x.jpg?v=1588805484
here4
Player left: Zdiggity
here1
here2 headphones
here3 https://www.mytrendyphone.eu/images/Forever-Music-Soul-BHS-300-Bluetooth-Headphones-with-Microphone-Black-5900495738110-17072019-01-p.jpg
here4
here1
here2 bouquet
here3 https://fyf.tac-cdn.net/images/products/small/TEV55-6.jpg?auto=webp&quality=25
here4
here1
here2 run
here3 https://health.clevelandclinic.org/wp-content/uploads/sites/3/2019/05/kidsRaceAge-891544116-770x553.jpg
here4
here1
here2 chef
here3 https://hips.hearstapps.com/cos.h-cdn.co/assets/15/44/1445864120-noreserations.jpg
here4
Game starting now!
here1
here2 taco
here3 https://www.carveyourcraving.com/wp-content/uploads/2020/09/Easy-vegetarian-tacos.jpg
here4
here1
here2 turkey
here3 https://cdn.vox-cdn.com/thumbor/MZdPtDWbDft-O51sbSdBSeekrDo=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22976864/merlin_358195.jpg
here4
here1
here2 spitball
here3 https://www.wikihow.com/images/thumb/4/4e/Make-Spitballs-Step-16.jpg/v4-460px-Make-Spitballs-Step-16.jpg
here4
Game starting now!
here1
here2 washington dc
here3 https://media.tacdn.com/media/attractions-splice-spp-674x446/07/01/28/64.jpg
here4
here1
here2 kite
here3 https://m.media-amazon.com/images/I/61LuGcGfpeL._AC_SL1500_.jpg
here4
here1
here2 heaven
here3 https://media.swncdn.com/cms/CW/31203-heaven-facebook.1200w.tn.jpg
here4
Game starting now!
here1
here2 man
here3 connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
Starting server!
Traceback (most recent call last):
  File "main.py", line 173, in <module>
    asyncio.get_event_loop().run_until_complete(start_server)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1086, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('159.89.122.203', 5678): address already in use
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 136, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
Starting server!
Player joined: Carson
Game will start soon
Player left: Carson
Reset lobby to waiting state
Player joined: joe
Game will start soon
Player left: joe
Reset lobby to waiting state
Player joined: joe
Game will start soon
Player joined: mark
Game starting now!
here1
here2 waffles
here3 https://www.thespruceeats.com/thmb/zSkXCTfff09brgf3Oq6qX2_TP-I=/3000x2000/filters:fill(auto,1)/sourdough-waffles-4797941-hero-01-72b98b861f5a440bb5ba7c4b3460de6d.jpg
here4
here1
here2 difference
here3 http://static1.squarespace.com/static/5ea7b9441d55a003e8164562/t/5ec2c478948c3c6a95ae64d8/1589822589959/1.+TD+Logo.png?format=1500w
here4
here1
here2 international
here3 https://leverageedu.com/blog/wp-content/uploads/2019/10/Career-in-International-Business-Management.jpg
here4
here1
here2 kill
here3 https://images-na.ssl-images-amazon.com/images/I/71-IvoMcnHL._RI_.jpg
here4
here1
here2 evidence
here3 https://www.keionline.org/wp-content/uploads/1997/01/Evidence-or-Evident.jpg
here4
here1
here2 plan
here3 https://assets.entrepreneur.com/content/3x2/2000/20150512050128-shutterstock-124904123.jpeg
here4
here1
here2 contact
here3 https://mlqmtwka8c9g.i.optimole.com/gOh5_1g.Ga1T~1cfa5/w:764/h:321/q:75/https://www.competethemes.com/wp-content/uploads/2016/01/add-contact-form.png
here4
here1
here2 society
here3 https://ssir.org/images/blog/SERIES-civil-society-Dan-Cardinali-equity-power-sharing592x333.jpg
here4
here1
here2 literature
here3 https://www.topuniversities.com/sites/default/files/articles/lead-images/What_Can_You_Do_With_an_English_Literature_Degree.jpg
here4
here1
here2 injury
here3 https://www.hopkinsmedicine.org/-/media/images/health/1_-conditions/bones-and-joints/elbow-injury-hero.ashx?h=500&iar=0&mh=500&mw=1300&w=1297&hash=2E1B17C64E2641F265C0808722AAC121
here4
here1
here2 picture
here3 https://media.istockphoto.com/photos/hot-air-balloons-flying-over-the-botan-canyon-in-turkey-picture-id1297349747?b=1&k=20&m=1297349747&s=170667a&w=0&h=oH31fJty_4xWl_JQ4OIQWZKP8C6ji9Mz7L4XmEnbqRU=
here4
here1
here2 itself
here3 https://logos.flamingtext.com/Word-Logos/itself-design-sketch-name.png
here4
here1
here2 applause
here3 https://thumbs.dreamstime.com/z/hands-clapping-applause-thumb-up-gesture-congratulations-concept-illustration-text-bravo-great-like-good-vector-hands-106557483.jpg
here4
here1
here2 christmas tree
here3 https://media.istockphoto.com/vectors/christmas-trees-set-isolated-on-white-background-vector-id1182200355?k=20&m=1182200355&s=612x612&w=0&h=Ms8MHeAQZmxrY_vnlwpVEHhNsDiu3xtbr67olESFGyo=
here4
here1
here2 conference
here3 https://www.ryerson.ca/content/dam/student-life-and-learning/Leadership/Optimized-ConferencePhoto1.jpg
here4
here1
here2 standard
here3 https://image.shutterstock.com/image-illustration/standards-complex-like-puzzle-pictured-260nw-1999254680.jpg
here4
here1
here2 poet
here3 https://guyanachronicle.com/wp-content/uploads/elementor/thumbs/poet-mxsmb913vkry85r5zsf5fm06p88pc175eozb9y1e6o.jpg
here4
here1
here2 like
here3 https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Likee.svg/1200px-Likee.svg.png
here4
here1
here2 balance
here3 https://www.sigarch.org/wp-content/uploads/2020/04/AdobeStock_86833018-1080x675.jpeg
here4
here1
here2 attention
here3 https://sph.lsuhsc.edu/wp-content/uploads/2020/03/Megaphone-Hand-business-concept-with-text-Attention-Please-1051350032_1735x1735.jpeg
here4
here1
here2 camera
here3 https://i.pcmag.com/imagery/roundups/018cwxjHcVMwiaDIpTnZJ8H-23.fit_lim.size_1200x630.v1570842461.jpg
here4
here1
here2 of
here3 https://i.ytimg.com/vi/ngq5Aw0Q6rQ/maxresdefault.jpg
here4
here1
here2 plan
here3 https://iacny.org/images/plan-dice-760.jpg
here4
here1
here2 reason
here3 https://tf-shop-media20210629093939227600000001.s3.amazonaws.com/product/rsn%3A85%2320/pictures/screen-Live1650.png.10000x10000_q85.png
here4
Game starting now!
here1
here2 blizzard
here3 https://www.farmersalmanac.com/wp-content/uploads/2021/01/blizzard-man-walking-winter-as_289632411.jpeg
here4
here1
here2 data
here3 https://images.squarespace-cdn.com/content/v1/5d5156083138fd000193c11a/1566843015800-H2LLPN9RVCO7I2MQH5X6/data-charts-man-601834022.jpg?format=1000w
here4
here1
here2 surface
here3 https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4prIF?ver=e8fb&q=90&m=8&h=431&w=767&b=%23FFFFFFFF&l=f&x=615&y=196&s=1505&d=846&aim=true
here4
here1
here2 quality
here3 https://s3.amazonaws.com/mentoring.redesign/s3fs-public/quality-level-meter.jpg
here4
here1
here2 traditional
here3 https://edkentmedia.com/wp-content/uploads/2018/01/traditional-marketing-vs-digital-marketing-1.png
here4
here1
here2 whisk
here3 https://www.thespruceeats.com/thmb/nV8mR76B2_MgWozIpQ1T8px_uAk=/1280x854/filters:no_upscale():max_bytes(150000):strip_icc()/whisk-56a1c6eb5f9b58b7d0c2843b.jpg
here4
here1
here2 flour
here3 https://www.verywellfit.com/thmb/7PEwp4VdUN1klShP4CmCsf2ug_g=/1500x1000/filters:fill(FFDB5D,1)/flour_annotated22-7efed342c2214cdaaaab001d1a6b204d.jpg
here4
here1
here2 manage
here3 https://cdn.business2community.com/wp-content/uploads/2015/08/time_manage_c-300x170.jpg.jpg
here4
here1
here2 floor
here3 https://dubeaufloors.com/wp-content/uploads/2000/02/hardwood-floor-dubeau-yellow-birch-select-and-better-natural.jpg
here4
here1
here2 childhood
here3 https://cdn.cdnparenting.com/articles/2018/02/636281354-H.jpg
here4
here1
here2 hockey
here3 https://images2.9c9media.com/image_asset/2022_1_27_14b73833-e2b3-4c43-a39f-2ee527db06d3_jpg_594x334.jpg?width=980&height=551
here4
here1
here2 criticism
here3 https://www.franksonnenbergonline.com/wp-content/uploads/2016/03/image_criticism-is-not-feedback.jpg
here4
here1
here2 bank
here3 https://upload.wikimedia.org/wikipedia/commons/5/5d/Bank_of_Montreal_Head_Office%2C_Montr%C3%A9al%2C_Southeast_view_20170410_1.jpg
here4
here1
here2 analysis
here3 https://scholarlykitchen.sspnet.org/wp-content/uploads/2015/07/options-analysis1.jpg
here4
here1
here2 mission
here3 https://fabrikbrands.com/wp-content/uploads/Company-Mission-Statement-1.jpg
here4
here1
here2 vehicle
here3 https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gettyimages-1214430325.jpg?crop=1.00xw:1.00xh;0,0&resize=640:*
here4
here1
here2 mouse
here3 https://m.media-amazon.com/images/I/71SkwkuaedL._AC_SL1500_.jpg
here4
here1
here2 meeting
here3 https://ehq-production-us-california.imgix.net/3aa184fc578b28f2551285532bb84326503960ad/projects/images/000/002/142/original/running-effective-meeting.jpg?auto=compress%2Cformat&w=1080
here4
here1
here2 everything
here3 https://qph.fs.quoracdn.net/main-qimg-074db757e170ab2b33c352635177387d
here4
here1
here2 report
here3 https://static.wixstatic.com/media/b11507_4a144943276543ccaa3776f6857ff47d~mv2.png/v1/fit/w_609%2Ch_349%2Cal_c/file.png
here4
here1
here2 passenger
here3 https://i.ytimg.com/vi/dgFZNFGMZ88/maxresdefault.jpg
here4
here1
here2 pass
here3 https://d36m266ykvepgv.cloudfront.net/uploads/media/sZsYFwelO7/s-660-400/capture-32.jpg
here4
here1
here2 kill
here3 https://image.winudf.com/v2/image1/bW9tby5raWxsLm1vbW9zLmZpbmQuY2hhbGxlbmdlLmdhbWVfc2NyZWVuXzBfMTU1Mzg0MDg3NV8wMTU/screen-0.jpg?fakeurl=1&type=.jpg
here4
here1
here2 outside
here3 https://assets3.thrillist.com/v1/image/2887781/1200x630/flatten;crop_down;webp=auto;jpeg_quality=70
here4
here1
here2 business
here3 https://www.incimages.com/uploaded_files/image/1920x1080/getty_180152187_970679970450042_64007.jpg
here4
Player left: joe
Player left: mark
Player joined: joe
Game will start soon
Player left: joe
Reset lobby to waiting state
Player joined: joe
Game will start soon
Player left: joe
Reset lobby to waiting state
Player joined: Paul
Game will start soon
Player joined: joe'
Player left: joe'
Player joined: joe
Game starting now!
here1
here2 eight
here3 https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=295850573903212
here4
here1
here2 out
here3 https://media-exp1.licdn.com/dms/image/C4D0BAQE2DJ-qZAsWOg/company-logo_200_200/0/1582140818291?e=2159024400&v=beta&t=qUUzqKnMzoAvY8l6OIyUB3oR-KEVIqZydSggB3waYrY
here4
here1
here2 address
here3 https://www.bluemarblegeo.com/knowledgebase/global-mapper-20/images/Dialogs/FindAddressResult.png
here4
here1
here2 truth
here3 connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 138, in time
    msg = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
connection handler failed
Traceback (most recent call last):
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 231, in handler
    await self.ws_handler(self)
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/server.py", line 1134, in _ws_handler
    return await cast(
  File "main.py", line 89, in time
    name = await socket.recv()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/sophie/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
